<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-05-08 01:05:58.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity\Continents
 *
 * @ORM\Entity(repositoryClass="App\Repositories\Continent\EloquentContinentRepository")
 * @ORM\Table(name="continents")
 */
class Continents
{
    /**
     * @var string
     *
     * @ORM\Column(name="code", type="string", length=2, nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $code;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;


    /**
     * Set the value of code.
     *
     * @param integer $code
     * @return \Entity\Continents
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get the value of code.
     *
     * @return integer
     */
    public function getCode()
    {
        return $this->code;
    }


    /**
     * Set the value of name.
     *
     * @param integer $name
     * @return \Entity\Continents
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get the value of name.
     *
     * @return integer
     */
    public function getName()
    {
        return $this->name;
    }

}

