<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-05-08 01:05:58.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Entity\Trip
 *
 * @ORM\Entity(repositoryClass="TripRepository")
 * @ORM\Table(name="trip", indexes={@ORM\Index(name="fk_trip_pays1_idx", columns={"pays_id"})})
 */
class Trip
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $transportId;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $userId;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $dateDepart;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $dateFin;

    /**
     * @ORM\Column(type="integer")
     */
    protected $pays_id;

    /**
     * @ORM\OneToOne(targetEntity="User", mappedBy="trip")
     */
    protected $user;

    /**
     * @ORM\OneToOne(targetEntity="Pays", inversedBy="trip")
     * @ORM\JoinColumn(name="pays_id", referencedColumnName="id", nullable=false)
     */
    protected $pays;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\Trip
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of transportId.
     *
     * @param integer $transportId
     * @return \Entity\Trip
     */
    public function setTransportId($transportId)
    {
        $this->transportId = $transportId;

        return $this;
    }

    /**
     * Get the value of transportId.
     *
     * @return integer
     */
    public function getTransportId()
    {
        return $this->transportId;
    }

    /**
     * Set the value of userId.
     *
     * @param integer $userId
     * @return \Entity\Trip
     */
    public function setUserId($userId)
    {
        $this->userId = $userId;

        return $this;
    }

    /**
     * Get the value of userId.
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Set the value of dateDepart.
     *
     * @param \DateTime $dateDepart
     * @return \Entity\Trip
     */
    public function setDateDepart($dateDepart)
    {
        $this->dateDepart = $dateDepart;

        return $this;
    }

    /**
     * Get the value of dateDepart.
     *
     * @return \DateTime
     */
    public function getDateDepart()
    {
        return $this->dateDepart;
    }

    /**
     * Set the value of dateFin.
     *
     * @param \DateTime $dateFin
     * @return \Entity\Trip
     */
    public function setDateFin($dateFin)
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    /**
     * Get the value of dateFin.
     *
     * @return \DateTime
     */
    public function getDateFin()
    {
        return $this->dateFin;
    }

    /**
     * Set the value of pays_id.
     *
     * @param integer $pays_id
     * @return \Entity\Trip
     */
    public function setPaysId($pays_id)
    {
        $this->pays_id = $pays_id;

        return $this;
    }

    /**
     * Get the value of pays_id.
     *
     * @return integer
     */
    public function getPaysId()
    {
        return $this->pays_id;
    }

    /**
     * Set User entity (one to one).
     *
     * @param \Entity\User $user
     * @return \Entity\Trip
     */
    public function setUser(User $user = null)
    {
        $user->setTrip($this);
        $this->user = $user;

        return $this;
    }

    /**
     * Get User entity (one to one).
     *
     * @return \Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set Pay entity (one to one).
     *
     * @param \Entity\Pay $pays
     * @return \Entity\Trip
     */
    public function setPays(Pay $pays)
    {
        $this->pays = $pays;

        return $this;
    }

    /**
     * Get Pay entity (one to one).
     *
     * @return \Entity\Pay
     */
    public function getPay()
    {
        return $this->pay;
    }

    public function __sleep()
    {
        return array('id', 'transportId', 'userId', 'dateDepart', 'dateFin', 'pays_id');
    }
}