<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-05-08 01:05:58.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity\User
 *
 * @ORM\Entity(repositoryClass="UserRepository")
 **/

 /* ORM\Table(name="`user`", indexes={@ORM\Index(name="fk_user_duty1_idx", columns={"duty_id", "duty_objet_id"}), @ORM\Index(name="fk_user_trip1_idx", columns={"trip_id"})})
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=60)
     */
    protected $nom;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $email;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    protected $password_hash;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $salt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $adresse;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $location_id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $telephone;

    /*
     * @ORM\Id
     * @ORM\Column(type="integer")
     
    protected $duty_id;

     * @ORM\Id
     * @ORM\Column(type="integer")
    protected $duty_objet_id;

     * @ORM\Column(type="integer")
    protected $trip_id;

     * @ORM\OneToOne(targetEntity="Duty", inversedBy="user")
     * @ORM\JoinColumns({@ORM\JoinColumn(name="duty_id", referencedColumnName="id", nullable=false),
     *     @ORM\JoinColumn(name="duty_objet_id", referencedColumnName="objet_id", nullable=false)
     * })
    protected $duty;

     * @ORM\OneToOne(targetEntity="Trip", inversedBy="user")
     * @ORM\JoinColumn(name="trip_id", referencedColumnName="id", nullable=false)
    protected $trip;
     */

    public function __construct()
    {
    }

    /**
     * Set the value of nom.
     *
     * @param string $nom
     * @return \Entity\User
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get the value of nom.
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set the value of prenom.
     *
     * @param string $prenom
     * @return \Entity\User
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get the value of prenom.
     *
     * @return string
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Set the value of email.
     *
     * @param string $email
     * @return \Entity\User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get the value of email.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set the value of password_hash.
     *
     * @param string $password_hash
     * @return \Entity\User
     */
    public function setPasswordHash($password_hash)
    {
        $this->password_hash = $password_hash;

        return $this;
    }

    /**
     * Get the value of password_hash.
     *
     * @return string
     */
    public function getPasswordHash()
    {
        return $this->password_hash;
    }

    /**
     * Set the value of salt.
     *
     * @param string $salt
     * @return \Entity\User
     */
    public function setSalt($salt)
    {
        $this->salt = $salt;

        return $this;
    }

    /**
     * Get the value of salt.
     *
     * @return string
     */
    public function getSalt()
    {
        return $this->salt;
    }

    /**
     * Set the value of adresse.
     *
     * @param string $adresse
     * @return \Entity\User
     */
    public function setAdresse($adresse)
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * Get the value of adresse.
     *
     * @return string
     */
    public function getAdresse()
    {
        return $this->adresse;
    }

    /**
     * Set the value of location_id.
     *
     * @param integer $location_id
     * @return \Entity\User
     */
    public function setLocationId($location_id)
    {
        $this->location_id = $location_id;

        return $this;
    }

    /**
     * Get the value of location_id.
     *
     * @return integer
     */
    public function getLocationId()
    {
        return $this->location_id;
    }

    /**
     * Set the value of telephone.
     *
     * @param string $telephone
     * @return \Entity\User
     */
    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * Get the value of telephone.
     *
     * @return string
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /*
     * Set the value of duty_id.
     *
     * @param integer $duty_id
     * @return \Entity\User
     
    public function setDutyId($duty_id)
    {
        $this->duty_id = $duty_id;

        return $this;
    }

     * Get the value of duty_id.
     *
     * @return integer
    public function getDutyId()
    {
        return $this->duty_id;
    }

    /**
     * Set the value of duty_objet_id.
     *
     * @param integer $duty_objet_id
     * @return \Entity\User
    public function setDutyObjetId($duty_objet_id)
    {
        $this->duty_objet_id = $duty_objet_id;

        return $this;
    }

     * Get the value of duty_objet_id.
     *
     * @return integer
    public function getDutyObjetId()
    {
        return $this->duty_objet_id;
    }

    /**
     * Set the value of trip_id.
     *
     * @param integer $trip_id
     * @return \Entity\User
    public function setTripId($trip_id)
    {
        $this->trip_id = $trip_id;

        return $this;
    }

    /**
     * Get the value of trip_id.
     *
     * @return integer
    public function getTripId()
    {
        return $this->trip_id;
    }

    /**
     * Set Duty entity (one to one).
     *
     * @param \Entity\Duty $duty
     * @return \Entity\User
    public function setDuty(Duty $duty)
    {
        $this->duty = $duty;

        return $this;
    }

    /**
     * Get Duty entity (one to one).
     *
     * @return \Entity\Duty
    public function getDuty()
    {
        return $this->duty;
    }

    /**
     * Set Trip entity (one to one).
     *
     * @param \Entity\Trip $trip
     * @return \Entity\User
    public function setTrip(Trip $trip)
    {
        $this->trip = $trip;

        return $this;
    }

    /**
     * Get Trip entity (one to one).
     *
     * @return \Entity\Trip
    public function getTrip()
    {
        return $this->trip;
    }
*/
    public function __sleep()
    {
        return array('nom', 'prenom', 'email', 'password_hash', 'salt', 'adresse', 'location_id', 'telephone');
            //'duty_id', 'duty_objet_id', 'trip_id');
    }

}