Creating database schema for default entity manager...
CREATE TABLE duty (id INT NOT NULL, objet_id INT NOT NULL, contenu VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, countries_list LONGTEXT DEFAULT NULL, is_free SMALLINT DEFAULT NULL, prix_minimum VARCHAR(45) DEFAULT NULL, prix_maximum VARCHAR(45) DEFAULT NULL, ultimatum_date VARCHAR(45) DEFAULT NULL, image LONGBLOB DEFAULT NULL, user_id VARCHAR(255) NOT NULL, INDEX fk_duty_objet1_idx (objet_id), PRIMARY KEY(id, objet_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;     
CREATE TABLE objet (id INT NOT NULL, nom VARCHAR(45) DEFAULT NULL, `desc` VARCHAR(255) DEFAULT NULL, countries_id INT DEFAULT NULL, local_prix VARCHAR(10) DEFAULT NULL, image LONGBLOB DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;     
CREATE TABLE continents (code VARCHAR(2) NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(code)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;     
CREATE TABLE trip (id INT NOT NULL, countries_id INT NOT NULL, transport_id INT DEFAULT NULL, user_id INT DEFAULT NULL, date_depart DATETIME DEFAULT NULL, date_fin DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_7656F53BAEBAE514 (countries_id), INDEX fk_trip_countries1_idx (countries_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;     
CREATE TABLE countries (country_id INT AUTO_INCREMENT NOT NULL, continent_code VARCHAR(2) DEFAULT NULL, code VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, full_name VARCHAR(128) NOT NULL, iso3 VARCHAR(3) NOT NULL, number SMALLINT NOT NULL, display_order INT NOT NULL, INDEX idx_continent_code (continent_code), UNIQUE INDEX idx_code (code), PRIMARY KEY(country_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;     
CREATE TABLE users (nom VARCHAR(60) NOT NULL, prenom VARCHAR(45) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, password_hash VARCHAR(255) DEFAULT NULL, remember_token VARCHAR(100) DEFAULT NULL, salt VARCHAR(45) DEFAULT NULL, adresse VARCHAR(255) DEFAULT NULL, location_id INT DEFAULT NULL, telephone VARCHAR(45) DEFAULT NULL, PRIMARY KEY(nom)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;     
ALTER TABLE duty ADD CONSTRAINT FK_A5B06099F520CF5A FOREIGN KEY (objet_id) REFERENCES objet (id);     
ALTER TABLE trip ADD CONSTRAINT FK_7656F53BAEBAE514 FOREIGN KEY (countries_id) REFERENCES countries (country_id);     
ALTER TABLE countries ADD CONSTRAINT FK_5D66EBAD16C569B FOREIGN KEY (continent_code) REFERENCES continents (code)
Database schema created successfully!
